# Generated by Django 4.2.4 on 2023-09-02 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bajo',
            options={'ordering': ['modelo'], 'verbose_name': 'Bajo', 'verbose_name_plural': 'Bajos'},
        ),
        migrations.AlterModelOptions(
            name='guitarra',
            options={'ordering': ['modelo'], 'verbose_name': 'Guitarra', 'verbose_name_plural': 'Guitarras'},
        ),
        migrations.AlterModelOptions(
            name='percusion',
            options={'ordering': ['modelo'], 'verbose_name': 'Percusion', 'verbose_name_plural': 'Percusiones'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['nombre'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
